### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by MateuszTyszkiewicz** [NNUG2019/KlasyfikacjaPatentow#2]
1. Trzeba sprawdzić, ile tych patentów jest.
2. Jak już będziemy wiedzieć ile tych patentów jest, to należy poznać strukturę jsona.
3. Sprawdzić, ile jest klas: pierwsze cztery litery to jest klasyfikacja główna (na tym się skupić). Wyciąć te pierwsze cztery litery. Sprawdzić, czy klasy są równoliczne. Sprawdzić cokolwiek, co jest ciekawe.

**Comment by Klaudiaww** [comment]
1. Zrobione
2. Zrobione chyba ?
3. Zostało sprawdzenie ciekawych rzeczy

**Comment by mknorps** [comment]
- CNN
- RNN
- HAN

artykuł Jatana na medium
