### ISSUE TITLE
Sprawdzić liczbę słów w każdym z patentów

### ISSUE THREAD

**Issue by MateuszTyszkiewicz** [NNUG2019/KlasyfikacjaPatentow#4]

**Comment by Klaudiaww** [comment]
@mknorps  Brak Dostępu

**Comment by MateuszTyszkiewicz** [comment]
@mknorps dzień dobry. Mamy problem z otwarciem w Pythonie naszego pliku. Próba otwarcia go w Spyderze kończy się crashem programu bez żadnego alertu.

**Comment by MateuszTyszkiewicz** [comment]
@mknorps udało nam się otworzyć plik w Jupyterze, ale:
- nie wiem, jak otworzyć ten plik w Google Colab, ponieważ nie wiem, jak określić ścieżkę do pliku znajdującego się na Dysku Google,
- udało mi się otworzyć plik w Spyderze, ale niezbyt wiem, jak go w tym programie obrabiać.

Prosilibyśmy o pomoc :)

**Comment by Klaudiaww** [comment]
@mknorps Dzień dobry.
Zdecydowaliśmy, że działamy na Jupyterze.  Obecnie mamy problem związany z obliczeniem liczby słów w patencie a konkretnie nie wiemy czy zliczać liczbę słów z  'abstract' czy 'description'.

Prosimy o pomoc :)

**Comment by ttylec** [comment]
google colab powinien stworzyć na waszym osobistym dysku google katalog Colab Notebooks, to co tam jest powinno się wyświetlić w zakładce Google Drive jak wejdziecie na stronę http://colab.research.google.com

Co do ostatniego pytania: można i tu i tu ;)

**Comment by mknorps** [comment]
+ Histogramy. Można porozmawiać o kodzie - jak to zrobić łatwiej jeżeli @Klaudiaww  i @Tysiu  są zainteresowani
